export const MUTATE_INIT_BASE_STATS = 'MUTATE_INIT_BASE_STATS';
export const MUTATE_BASE_STATS = 'MUTATE_BASE_STATS';
export const MUTATE_SETTINGS = 'MUTATE_SETTINGS';
export const MUTATE_POINTS = 'MUTATE_POINTS';
